services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - todo_mongo_data:/data/db

  api:
    build: ./backend-mongo
    environment:
      MONGO_URL: mongodb://mongo:27017
      MONGO_DB: todo
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
  todo_mongo_data:
